create table public.mailing_list (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) > 0),
  email text not null unique check (email = lower(email)),
  created_at timestamptz not null default now()
);

alter table public.mailing_list enable row level security;
